import { Employee, AttendanceRecord, LeaveRequest, PayrollRecord, DocumentItem, NotificationItem } from './types';

export const INITIAL_EMPLOYEES: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'EMP001',
    name: 'Alex Morgan',
    email: 'alex.morgan@dayflow.com',
    role: 'EMPLOYEE',
    department: 'Engineering',
    designation: 'Senior Frontend Engineer',
    joiningDate: '2023-03-15',
    phone: '+1 (555) 234-5678',
    address: '742 Evergreen Terrace, San Francisco, CA 94107',
    avatarUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    status: 'ACTIVE',
    salary: {
      basicPay: 6500,
      hra: 2500,
      allowances: 1200,
      deductions: 800,
      netSalary: 9400,
    },
  },
  {
    id: 'emp-2',
    employeeId: 'EMP002',
    name: 'Sarah Connor',
    email: 'sarah.connor@dayflow.com',
    role: 'ADMIN',
    department: 'Human Resources',
    designation: 'HR Lead & Administrator',
    joiningDate: '2022-01-10',
    phone: '+1 (555) 876-5432',
    address: '100 Cyberdyne Way, Austin, TX 78701',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    status: 'ACTIVE',
    salary: {
      basicPay: 7000,
      hra: 2800,
      allowances: 1500,
      deductions: 900,
      netSalary: 10400,
    },
  },
  {
    id: 'emp-3',
    employeeId: 'EMP003',
    name: 'Marcus Vance',
    email: 'marcus.vance@dayflow.com',
    role: 'EMPLOYEE',
    department: 'Product Design',
    designation: 'Lead UI/UX Designer',
    joiningDate: '2023-07-01',
    phone: '+1 (555) 345-6789',
    address: '404 Innovation Blvd, Seattle, WA 98101',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    status: 'ACTIVE',
    salary: {
      basicPay: 6000,
      hra: 2200,
      allowances: 1000,
      deductions: 750,
      netSalary: 8450,
    },
  },
  {
    id: 'emp-4',
    employeeId: 'EMP004',
    name: 'Elena Rostova',
    email: 'elena.rostova@dayflow.com',
    role: 'EMPLOYEE',
    department: 'Engineering',
    designation: 'Backend Systems Engineer',
    joiningDate: '2024-02-01',
    phone: '+1 (555) 456-7890',
    address: '120 Market St, New York, NY 10001',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150',
    status: 'ACTIVE',
    salary: {
      basicPay: 6200,
      hra: 2400,
      allowances: 1100,
      deductions: 780,
      netSalary: 8920,
    },
  },
  {
    id: 'emp-5',
    employeeId: 'EMP005',
    name: 'David Chen',
    email: 'david.chen@dayflow.com',
    role: 'EMPLOYEE',
    department: 'Marketing',
    designation: 'Growth Marketing Specialist',
    joiningDate: '2023-11-15',
    phone: '+1 (555) 567-8901',
    address: '888 Broadway Ave, Chicago, IL 60601',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    status: 'ACTIVE',
    salary: {
      basicPay: 5200,
      hra: 1900,
      allowances: 800,
      deductions: 600,
      netSalary: 7300,
    },
  },
];

export const INITIAL_ATTENDANCE: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'EMP001',
    employeeName: 'Alex Morgan',
    date: '2026-08-22',
    checkInTime: '09:02 AM',
    checkOutTime: undefined,
    workHours: 4.5,
    status: 'PRESENT',
    notes: 'On time',
  },
  {
    id: 'att-2',
    employeeId: 'EMP001',
    employeeName: 'Alex Morgan',
    date: '2026-08-21',
    checkInTime: '08:58 AM',
    checkOutTime: '05:30 PM',
    workHours: 8.5,
    status: 'PRESENT',
  },
  {
    id: 'att-3',
    employeeId: 'EMP001',
    employeeName: 'Alex Morgan',
    date: '2026-08-20',
    checkInTime: '09:15 AM',
    checkOutTime: '05:45 PM',
    workHours: 8.5,
    status: 'PRESENT',
  },
  {
    id: 'att-4',
    employeeId: 'EMP001',
    employeeName: 'Alex Morgan',
    date: '2026-08-19',
    checkInTime: '09:00 AM',
    checkOutTime: '01:00 PM',
    workHours: 4.0,
    status: 'HALF_DAY',
    notes: 'Doctor appointment in afternoon',
  },
  {
    id: 'att-5',
    employeeId: 'EMP002',
    employeeName: 'Sarah Connor',
    date: '2026-08-22',
    checkInTime: '08:45 AM',
    checkOutTime: undefined,
    workHours: 4.8,
    status: 'PRESENT',
  },
  {
    id: 'att-6',
    employeeId: 'EMP003',
    employeeName: 'Marcus Vance',
    date: '2026-08-22',
    checkInTime: undefined,
    checkOutTime: undefined,
    workHours: 0,
    status: 'LEAVE',
    notes: 'Approved Paid Leave',
  },
  {
    id: 'att-7',
    employeeId: 'EMP004',
    employeeName: 'Elena Rostova',
    date: '2026-08-22',
    checkInTime: '09:10 AM',
    checkOutTime: undefined,
    workHours: 4.3,
    status: 'PRESENT',
  },
  {
    id: 'att-8',
    employeeId: 'EMP005',
    employeeName: 'David Chen',
    date: '2026-08-22',
    checkInTime: undefined,
    checkOutTime: undefined,
    workHours: 0,
    status: 'ABSENT',
  },
];

export const INITIAL_LEAVES: LeaveRequest[] = [
  {
    id: 'lv-1',
    employeeId: 'EMP001',
    employeeName: 'Alex Morgan',
    department: 'Engineering',
    leaveType: 'PAID',
    startDate: '2026-08-28',
    endDate: '2026-08-30',
    totalDays: 3,
    reason: 'Family vacation trip planned for weekend.',
    status: 'PENDING',
    appliedDate: '2026-08-20',
  },
  {
    id: 'lv-2',
    employeeId: 'EMP003',
    employeeName: 'Marcus Vance',
    department: 'Product Design',
    leaveType: 'PAID',
    startDate: '2026-08-22',
    endDate: '2026-08-23',
    totalDays: 2,
    reason: 'Attending Design Leadership Conference.',
    status: 'APPROVED',
    appliedDate: '2026-08-15',
    adminComment: 'Approved. Enjoy the conference!',
    reviewedBy: 'Sarah Connor',
  },
  {
    id: 'lv-3',
    employeeId: 'EMP004',
    employeeName: 'Elena Rostova',
    department: 'Engineering',
    leaveType: 'SICK',
    startDate: '2026-08-10',
    endDate: '2026-08-11',
    totalDays: 2,
    reason: 'High fever and viral infection.',
    status: 'APPROVED',
    appliedDate: '2026-08-09',
    adminComment: 'Get well soon!',
    reviewedBy: 'Sarah Connor',
  },
  {
    id: 'lv-4',
    employeeId: 'EMP005',
    employeeName: 'David Chen',
    department: 'Marketing',
    leaveType: 'UNPAID',
    startDate: '2026-09-01',
    endDate: '2026-09-05',
    totalDays: 5,
    reason: 'Personal urgent matters.',
    status: 'PENDING',
    appliedDate: '2026-08-21',
  },
];

export const INITIAL_PAYROLL: PayrollRecord[] = [
  {
    id: 'pay-1',
    employeeId: 'EMP001',
    employeeName: 'Alex Morgan',
    department: 'Engineering',
    month: 'August 2026',
    basicPay: 6500,
    hra: 2500,
    allowances: 1200,
    deductions: 800,
    netSalary: 9400,
    paymentStatus: 'PAID',
    payDate: '2026-08-01',
  },
  {
    id: 'pay-2',
    employeeId: 'EMP002',
    employeeName: 'Sarah Connor',
    department: 'Human Resources',
    month: 'August 2026',
    basicPay: 7000,
    hra: 2800,
    allowances: 1500,
    deductions: 900,
    netSalary: 10400,
    paymentStatus: 'PAID',
    payDate: '2026-08-01',
  },
  {
    id: 'pay-3',
    employeeId: 'EMP003',
    employeeName: 'Marcus Vance',
    department: 'Product Design',
    month: 'August 2026',
    basicPay: 6000,
    hra: 2200,
    allowances: 1000,
    deductions: 750,
    netSalary: 8450,
    paymentStatus: 'PAID',
    payDate: '2026-08-01',
  },
  {
    id: 'pay-4',
    employeeId: 'EMP004',
    employeeName: 'Elena Rostova',
    department: 'Engineering',
    month: 'August 2026',
    basicPay: 6200,
    hra: 2400,
    allowances: 1100,
    deductions: 780,
    netSalary: 8920,
    paymentStatus: 'PAID',
    payDate: '2026-08-01',
  },
  {
    id: 'pay-5',
    employeeId: 'EMP005',
    employeeName: 'David Chen',
    department: 'Marketing',
    month: 'August 2026',
    basicPay: 5200,
    hra: 1900,
    allowances: 800,
    deductions: 600,
    netSalary: 7300,
    paymentStatus: 'PENDING',
  },
];

export const INITIAL_DOCUMENTS: DocumentItem[] = [
  {
    id: 'doc-1',
    employeeId: 'EMP001',
    title: 'Employment Offer Letter & Contract.pdf',
    category: 'CONTRACT',
    fileUrl: '#',
    uploadDate: '2023-03-15',
    size: '1.4 MB',
  },
  {
    id: 'doc-2',
    employeeId: 'EMP001',
    title: 'W-4 Tax Declaration 2026.pdf',
    category: 'TAX',
    fileUrl: '#',
    uploadDate: '2026-01-10',
    size: '680 KB',
  },
  {
    id: 'doc-3',
    employeeId: 'EMP001',
    title: 'August 2026 Salary Slip.pdf',
    category: 'PAYSLIP',
    fileUrl: '#',
    uploadDate: '2026-08-01',
    size: '340 KB',
  },
  {
    id: 'doc-4',
    employeeId: 'EMP001',
    title: 'Passport & Identity Verification.pdf',
    category: 'IDENTIFICATION',
    fileUrl: '#',
    uploadDate: '2023-03-15',
    size: '2.8 MB',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    userId: 'EMP001',
    title: 'Leave Application Received',
    message: 'Your leave request for Aug 28 - Aug 30 has been submitted and is pending HR approval.',
    type: 'INFO',
    timestamp: '2026-08-20T10:30:00Z',
    read: false,
  },
  {
    id: 'notif-2',
    userId: 'EMP001',
    title: 'August Salary Credit',
    message: 'Your monthly salary for August 2026 of $9,400 has been processed.',
    type: 'SUCCESS',
    timestamp: '2026-08-01T08:00:00Z',
    read: true,
  },
  {
    id: 'notif-3',
    userId: 'EMP001',
    title: 'Company All-Hands Meeting',
    message: 'Q3 Town Hall scheduled for Friday at 3:00 PM EST.',
    type: 'INFO',
    timestamp: '2026-08-18T14:15:00Z',
    read: true,
  },
];
